{% set cudnn_version= "8.0.4.30" %}
{% set build_number= "0" %}
# The cuDNN installers can be downloaded from https://developer.nvidia.com/cudnn
# The download requires authetication, for this recipe to work download the
# packages to an staging location and adjust src_dir to this location.
{% set src_dir = "file:///home/user/Downloads" %}

package:
  name: cudnn
  version: 8.0.4

source:
  url: {{ src_dir }}/cudnn-{{ cuda_version }}-linux-x64-v{{ cudnn_version }}.tgz      # [linux]
  # NOTE: Only 8.0.4 is released for 10.1/10.2/11.0/11.1
  sha256: eb4b888e61715168f57a0a0a21c281ada6856b728e5112618ed15f8637487715            # [linux and cuda_version=='10.1']
  sha256: c12c69eb16698eacac40aa46b9ce399d4cd86efb6ff0c105142f8a28fcfb980e            # [linux and cuda_version=='10.2']
  sha256: 38a81a28952e314e21577432b0bab68357ef9de7f6c8858f721f78df9ee60c35            # [linux and cuda_version=='11.0']
  sha256: 8f4c662343afce5998ce963500fe3bb167e9a508c1a1a949d821a4b80fa9beab            # [linux and cuda_version=='11.1']
  url: {{ src_dir }}/cudnn-{{ cuda_version }}-windows10-x64-v{{ cudnn_version }}.zip  # [win64]
  # NOTE: Only 8.0.4 is released for 11.0/11.1
  sha256: 1b1438b828ce61888b7f1ed3ac506b32137425dd48aed8bc71abd5d4a7006143            # [win and cuda_version=='11.0']
  sha256: 58bf1fb324d11088a28c3a9f71a38f5dfe167efdf723815dce1867bc03ddaea2            # [win and cuda_version=='11.1']

build:
  skip: True  # [not linux64 and not win64]
  number: {{ build_number }}
  string: cuda{{ cuda_version }}_{{ build_number }}
  missing_dso_whitelist:
    - '*'
  run_exports:
    - {{ pin_subpackage('cudnn', min_pin='x.x', max_pin='x') }}

requirements:
  run:
    - cudatoolkit >=10.1,<10.2  # [cuda_version=='10.1']
    - cudatoolkit >=10.2,<10.3  # [cuda_version=='10.2']
    - cudatoolkit >=11.0,<11.1  # [cuda_version=='11.0']
    - cudatoolkit >=11.1,<11.2  # [cuda_version=='11.1']

test:
  commands:
    - test -f ${PREFIX}/lib/libcudnn.so                   # [linux]
    - test -f ${PREFIX}/lib/libcudnn.so.8                 # [linux]
    - test -f ${PREFIX}/lib/libcudnn.so.8.0.4             # [linux]
    - test -f ${PREFIX}/include/cudnn.h                   # [linux]
    - if not exist %LIBRARY_INC%\\cudnn.h exit 1          # [win]
    - if not exist %LIBRARY_LIB%\\x64\\cudnn.lib exit 1   # [win]
    - if not exist %LIBRARY_BIN%\\cudnn64_8.dll exit 1    # [win]

about:
  license: NVIDIA cuDNN Software License Agreement
  license_file: NVIDIA_SLA
  license_url: https://docs.nvidia.com/deeplearning/cudnn/sla/index.html
  description: |
    NVIDIA CUDA Deep Neural Network (cuDNN) is a GPU-accelerated library of primitives for deep neural networks. It provides highly tuned implementations of routines arising frequently in DNN applications.

    License Agreements: The packages are governed by the NVIDIA cuDNN Software License Agreement (SLA). By downloading and using the packages, you accept the terms and conditions of the NVIDIA cuDNN SLA - https://docs.nvidia.com/deeplearning/cudnn/sla/index.html
  summary: "NVIDIA's cuDNN deep neural network acceleration library"
  doc_url: https://docs.nvidia.com/deeplearning/cudnn
  dev_url: https://developer.nvidia.com/cudnn
